apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jde03zi5b-dotnet-basic
  janus-idp.io/tekton: jde03zi5b-dotnet-basic
  backstage.io/kubernetes-id: jde03zi5b-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jde03zi5b-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
